/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import modelo.Pelicula;
import persistencia.PeliculaData;

/**
 *
 * @author fatimaalcaraz
 */
public class gestionPelicula extends javax.swing.JInternalFrame {

    private PeliculaData peliData= new PeliculaData();
    private Pelicula pelicula= new Pelicula();
  
    public gestionPelicula() {
        initComponents();
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
       
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        rbCartelera = new javax.swing.JRadioButton();
        jtTitulo = new javax.swing.JTextField();
        jtDirector = new javax.swing.JTextField();
        jtActores = new javax.swing.JTextField();
        jtOrigen = new javax.swing.JTextField();
        jtGenero = new javax.swing.JTextField();
        calendario = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Gestion de Peliculas");

        jLabel2.setText("Titulo");

        jLabel3.setText("Director");

        jLabel4.setText("Origen");

        jLabel5.setText("Genero");

        jLabel6.setText("Actores");

        jLabel7.setText("Estreno");

        jLabel8.setText("En Cartelera");

        jtTitulo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtTituloFocusLost(evt);
            }
        });
        jtTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtTituloActionPerformed(evt);
            }
        });

        jtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtDirectorActionPerformed(evt);
            }
        });

        jtGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtGeneroActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)))))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jtGenero, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtOrigen, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtActores, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtDirector, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jtTitulo))
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rbCartelera))
                                .addGap(0, 159, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addComponent(jLabel1)))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnGuardar)
                .addGap(75, 75, 75)
                .addComponent(btnActualizar)
                .addGap(74, 74, 74)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtActores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel7))
                    .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(rbCartelera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnSalir))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
       if(jtTitulo.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Debe ingresar un titulo");
           return;
       }
       
        String titulo= (String) jtTitulo.getText();
       pelicula= peliData.buscarPeliculaPorTitulo(titulo);
       if(pelicula==null){
      // JOptionPane.showMessageDialog(null,"Pelicula vacia");
       limpiarCampos();
       
       }else{
            
       if(!pelicula.getTitulo().equalsIgnoreCase(titulo)){
           
                    JOptionPane.showMessageDialog(null,"No existe la pelicula");
                    jtTitulo.requestFocus();
                    limpiarCampos();
             
            }else{
                    
            jtDirector.setText(pelicula.getDirector());
            jtActores.setText(pelicula.getActores());
            jtOrigen.setText(pelicula.getOrigen());
            jtGenero.setText(pelicula.getGenero());
            calendario.setDate(Date.valueOf(pelicula.getEstreno()));
            rbCartelera.setSelected(pelicula.isEnCartelera());
            btnGuardar.setEnabled(false);
            btnEliminar.setEnabled(true);
            btnActualizar.setEnabled(true);
           
            }
                
            
       }
        
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void jtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtDirectorActionPerformed

    private void jtGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtGeneroActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if(jtTitulo.getText().isEmpty()|| jtDirector.getText().isEmpty()|| jtActores.getText().isEmpty()|| jtOrigen.getText().isEmpty()||
                jtGenero.getText().isEmpty()||calendario.getDate()== null ||!rbCartelera.isSelected()){
           JOptionPane.showMessageDialog(null, "complete todos los campos");
           return;
       }
        
        String titulo= jtTitulo.getText();
       
        
       String director = jtDirector.getText();
       String actores = jtActores.getText();
       String origen = jtOrigen.getText();
       String genero = jtGenero.getText();
       LocalDate estreno= calendario.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       boolean cartelera= rbCartelera.isSelected();
        
       if(director.matches("[a-zA-Z ]+")&& 
               actores.matches("[a-zA-Z ]+")&& origen.matches("[a-zA-Z]+")&&
                 genero.matches("[a-zA-Z]+")&& estreno!=null && cartelera==true){
        
            Pelicula peli= new Pelicula(titulo, director, actores, origen, genero, estreno, cartelera);
         peliData.guardarPelicula(peli);
        jtDirector.requestFocus();
         }else{
           
      
        JOptionPane.showMessageDialog(null, "revise, datos incorrectos ");
        
        
       }
       
       
        
        
      
    //   limpiarCampos();
        
        
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
       if(jtTitulo.getText().isEmpty()|| jtDirector.getText().isEmpty()|| jtActores.getText().isEmpty()|| jtOrigen.getText().isEmpty()||
                jtGenero.getText().isEmpty()||calendario.getDate()== null ||!rbCartelera.isSelected()){
           JOptionPane.showMessageDialog(null, "complete todos los campos");
           return;
       }
       
       
        String titulo= jtTitulo.getText();
       String director = jtDirector.getText();
       String actores = jtActores.getText();
       String origen = jtOrigen.getText();
       String genero = jtGenero.getText();
       LocalDate estreno= calendario.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
       boolean cartelera= rbCartelera.isSelected();
         if(director.matches("[a-zA-Z ]+")&& actores.matches("[a-zA-Z ]+")&& origen.matches("[a-zA-Z ]+")&&
                 genero.matches("[a-zA-Z ]+")&& estreno!=null ){
        Pelicula peli2= new Pelicula(titulo, director, actores, origen, genero, estreno, cartelera);
              peliData.actualizarPelicula(peli2);
         }else{
        JOptionPane.showMessageDialog(null, "revise, datos incorrectos ");
        jtDirector.requestFocus();
        
        
       }
      
 
        limpiarCampos();
        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
        
        
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       
        String titulo= jtTitulo.getText();
      
        peliData.borrarPelicula(titulo);
        limpiarCampos();
        btnGuardar.setEnabled(true);
        btnActualizar.setEnabled(false);
        btnEliminar.setEnabled(false);
       
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void jtTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtTituloActionPerformed

    private void jtTituloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtTituloFocusLost
           
       
               
        
    }//GEN-LAST:event_jtTituloFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private com.toedter.calendar.JDateChooser calendario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtActores;
    private javax.swing.JTextField jtDirector;
    private javax.swing.JTextField jtGenero;
    private javax.swing.JTextField jtOrigen;
    private javax.swing.JTextField jtTitulo;
    private javax.swing.JRadioButton rbCartelera;
    // End of variables declaration//GEN-END:variables


private void limpiarCampos(){
        jtTitulo.setText("");
        jtDirector.setText("");
        jtActores.setText("");
        jtOrigen.setText("");
        jtGenero.setText("");
        calendario.setDate((null));
        rbCartelera.setSelected(false);

}





}
