/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas1;

import java.time.LocalDateTime;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Funcion;
import modelo.Sala;
import persistencia.FuncionData;

/**
 *
 * @author Brian D
 */
public class ActualizarFunciones extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
     private  FuncionData funcionData;
      private Funcion funcion1;
    
    public ActualizarFunciones() {
            modelo= new DefaultTableModel();
      funcion1 = new Funcion();
      funcionData = new FuncionData();
        
        initComponents();
     
   
        armarTabla();
           cargarTabla();
      
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtTabla = new javax.swing.JTable();
        jnEliminar = new javax.swing.JButton();
        jbActualizar = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("actualizar funcioones");

        jtTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id_funcion", "Titulo", "Idioma", "es3D", "Subtitulada", "HoraInicio", "HoraFin", "numSala"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtTabla);

        jnEliminar.setText("Eliminar");
        jnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnEliminarActionPerformed(evt);
            }
        });

        jbActualizar.setText("Actualizar");
        jbActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActualizarActionPerformed(evt);
            }
        });

        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jbActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jnEliminar)
                    .addComponent(jbActualizar)
                    .addComponent(jbSalir))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActualizarActionPerformed
        int fila2 = jtTabla.getSelectedRow();
      if(fila2!=-1){ 
           int idFuncion = (int) jtTabla.getValueAt(fila2, 0);
           
          

      }
    }//GEN-LAST:event_jbActualizarActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnEliminarActionPerformed
       
      int fila = jtTabla.getSelectedRow();
      if(fila!=-1){
        
       
     int idFuncion = (int) jtTabla.getValueAt(fila, 0);
    
     
     funcionData.EliminarFuncion(idFuncion);
     
     
      }else{
       JOptionPane.showMessageDialog(this,"Debe seleccionar una fila");
      }
                  
          
    
          
          
      
      
          
        
    }//GEN-LAST:event_jnEliminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbActualizar;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jnEliminar;
    private javax.swing.JTable jtTabla;
    // End of variables declaration//GEN-END:variables

    
    private void armarTabla(){

    modelo.addColumn("idFuncion");
    modelo.addColumn("titulo");
    modelo.addColumn("idioma");
    modelo.addColumn("3D");
    modelo.addColumn("Subtitulada");
    modelo.addColumn("HoraDeInicio");
    modelo.addColumn("HoraDeFin");
     modelo.addColumn("Sala");
     jtTabla.setModel(modelo);

}
    public void cargarTabla(){
    
        for (Funcion funci : funcionData.listarFunciones()) {
            modelo.addRow(new Object[]{
                funci.getIdFuncion(),
                funci.getTitulo(),
                funci.getIdioma(),
                funci.isEs3D(),
                funci.isSubtitulada(),
                funci.getHoraDeInicio(),
                funci.getHoraDeFin(),
                funci.getSala()
                
               
            
                    
                    });
            
        }
    
    
    }
}
