
package vistas1;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Funcion;
import modelo.Lugar;
import persistencia.LugarData;

/**
 *
 * @author Gaby
 */
public class ButacaArreglo extends javax.swing.JInternalFrame {

    
    
    private static final int FILAS=5;
    private static final int COLUMNAS=8;
    private Funcion funcion;
    private JButton[][] botones;
    private Lugar[][] lugares;
    private LugarData lugardata;

    public ButacaArreglo() {
        
        
        
        
        
    }
    
    
    
    
    public ButacaArreglo(Funcion funcion,LugarData lugardata){
        
     
    super("Seleccion de Butacas ", false,true,false,false);
    
     initComponents();
     
    this.funcion = funcion;
    this.lugardata = lugardata;
    
    setSize(700,500);
    
    setLayout(new BorderLayout());
    
    crearGrillaButacas();
    
    setVisible(true);
    
   
    
    }

    
    
    
    
    private void crearGrillaButacas(){
    JPanel panel=new JPanel(new GridLayout(FILAS,COLUMNAS,5,8));
    
    panel.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
    
    botones=new JButton[FILAS][COLUMNAS];
    
    lugares=new Lugar[FILAS][COLUMNAS];
    
    List <Lugar> listaLugares = lugardata.lugaresXfuncion(funcion.getIdFuncion());
    
    
    
    
    
         for (Lugar aux: listaLugares) {
              int fila =aux.getFila()-1;
             int columna= aux.getNumero()-1;
                      
             lugares[fila][columna] = aux;
             
         }
            
             // CREAMOS 40 BOTONES 
             for (int f=0;f<FILAS;f++){
             for (int c=0; c<COLUMNAS;c++){
               
                 
                 Lugar lugar=lugares[f][c];
                 
                 String etiqueta="F" + (f+1) + "C" + (c+1);
                 
                 JButton btn=new JButton(etiqueta);
                 
                 btn.setFocusPainted(false);
                 
                 
                 
                 
                 if(lugar!=null){
                 
                 if(lugar.isEstado()){
                 btn.setBackground(Color.GREEN);
                 btn.setEnabled(true);
                 
                 
                 } else{
                 
                 btn.setBackground(Color.RED);
                 btn.setEnabled(false);
                 
                 }
                
                                                 
                 
                 }
                 
                 else{
                 
                 btn.setBackground(Color.LIGHT_GRAY);
                 btn.setEnabled(false);
                 
                 
                 }
             

            int fila = f;
            int columna=c;
            
            btn.addActionListener(e -> seleccionarButaca(fila,columna)); 
            botones[f][c]=btn;
            
            panel.add(btn);
         }
            
           add(panel,BorderLayout.CENTER);
            
            repaint();
            
            }

    }
    private List<Lugar> seleccionadas = new ArrayList();               
    
    
   
    private void seleccionarButaca(int f, int c) {
    JButton btn = botones[f][c];
    Lugar lugar = lugares[f][c];

    // Si el lugar está disponible (verde)
    if (lugar.isEstado()) {
        btn.setBackground(Color.YELLOW); // seleccionado
        lugar.setEstado(false); // marcarlo como reservado temporalmente
        seleccionadas.add(lugar);
    } else {
        // Si ya estaba seleccionado o ocupado
        btn.setBackground(Color.GREEN);
        lugar.setEstado(true);
        seleccionadas.remove(lugar);
    }
}
    
       
    
    
    
    
    
    
    
    

    public List<Lugar> getSeleccionadas() {
        return seleccionadas;
    }
    
  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
