
package vistas1;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import modelo.Funcion;
import modelo.Lugar;
import persistencia.LugarData;

/**
 *
 * @author Gaby
 */
public class ButacaArreglo extends javax.swing.JInternalFrame {

    
    private static final int FILAS=5;
    private static final int COLUMNAS=8;
    private Funcion funcion;
    private JButton[][] botones;
    private Lugar[][] lugares;
    private LugarData lugardata;
    
    public ButacaArreglo(Funcion funcion,LugarData lugardata){
        
     
    super("Seleccion de Butacas ", false,true,false,false);
    
     initComponents();
     
    this.funcion = funcion;
    this.lugardata = lugardata;
    
    setSize(700,500);
    
    setLayout(new BorderLayout());
    
    crearGrillaButacas();
    
    setVisible(true);
    
   
    
    }
    
    
    
    private void crearGrillaButacas(){
    JPanel panel=new JPanel(new GridLayout(FILAS,COLUMNAS,5,5));
    
    panel.setBorder(BorderFactory.createEmptyBorder(10,10,10,10));
    
    botones=new JButton[FILAS][COLUMNAS];
    
    lugares=new Lugar[FILAS][COLUMNAS];
    
    List <Lugar> listaLugares = lugardata.lugaresXfuncion(funcion.getIdFuncion());
    
    
         for (Lugar aux: listaLugares) {
             
             int fila =aux.getFila()-1;
             int columna= aux.getNumero()-1;
             
             lugares[fila][columna] = aux;
             
            JButton btn=new JButton("F" + aux.getFila() + "C" + aux.getNumero());
            
            if(aux.isEstado()){
            btn.setBackground(Color.GREEN);
            
            
            }else {
                
            btn.setBackground(Color.RED);
            btn.setEnabled(aux.isEstado());
            btn.setFocusPainted(false);
            }
            int f = fila;
            int c = columna;
            
            btn.addActionListener(e -> seleccionarButaca(f,c)); 
            botones[fila][columna]=btn;
            
            panel.add(btn);
         }
            
           add(panel,BorderLayout.CENTER);
            
            repaint();
            
            }
           
                   
    
    
    private void seleccionarButaca(int fila,int col){
   
     
    Lugar lugar=lugares[fila][col];
    
    JButton boton=botones[fila][col];
    
    
    if(lugar.isEstado()){
    
   
    
        boton.setBackground(Color.RED);

        boton.setEnabled(false);

        lugar.setEstado(false);
        lugardata.actualizarEstado(lugar.getCodLugar(),false);
    
    
    } else{
    
        JOptionPane.showMessageDialog(this,"Butaca no disponible");
        }
    
    
    }
    
  
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 274, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
