/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas1;

import java.time.LocalDate;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import modelo.Pelicula;
import persistencia.PeliculaData;

/**
 *
 * @author Brian D
 */
public class listaPeliculas extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo;
    private PeliculaData peliData;
    
    
    
    public listaPeliculas() {
        initComponents();
       modelo=  new DefaultTableModel();
       peliData= new PeliculaData();
       armarCabecera();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbPeliculas = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Peliculas disponibles");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbSalir.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jbSalir.setText("Salir");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Elija una opcion");

        cbPeliculas.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        cbPeliculas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En Cartelera", "Fuera de cartelera" }));
        cbPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPeliculasActionPerformed(evt);
            }
        });

        jButton1.setText("Baja");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(189, 189, 189))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel2)
                        .addGap(104, 104, 104)
                        .addComponent(cbPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cbPeliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed
       dispose();
    }//GEN-LAST:event_jbSalirActionPerformed

    private void cbPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPeliculasActionPerformed
       
        String cartelera= (String)cbPeliculas.getSelectedItem();
        boolean seleccion= true;
        
        if(cartelera.equalsIgnoreCase("En Cartelera")){
            seleccion= true;
        }else if(cartelera.equalsIgnoreCase("Fuera de Cartelera")){
            seleccion= false;
        }
        
        borrarFilas();
        
        for (Pelicula pelis : peliData.listarPeliculas()) {
            
            if( seleccion == pelis.isEnCartelera()){
                
   
             modelo.addRow(new Object[]{
             pelis.getTitulo(),
             pelis.getDirector(),
             pelis.getActores(),
             pelis.getOrigen(),
             pelis.getGenero(),
             pelis.getEstreno(),
             pelis.isEnCartelera()
        }); 
            
            }
            
        }
        
        
        
    }//GEN-LAST:event_cbPeliculasActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
        int fila = jTable1.getSelectedRow();
            if(fila!=-1){
             String titulo = (String) jTable1.getValueAt(fila,0);
             String director = (String) jTable1.getValueAt(fila, 1);
             String actores = (String) jTable1.getValueAt(fila, 2);
             String origen = (String) jTable1.getValueAt(fila, 3);
             String genero = (String) jTable1.getValueAt(fila, 4);
             LocalDate estreno = (LocalDate) jTable1.getValueAt(fila, 5);
             Boolean enCartelera = (boolean) jTable1.getValueAt(fila, 6);
             
             Pelicula peli = new Pelicula(titulo,director,actores,origen,genero,estreno,enCartelera);
             peliData.bajaLogicaPelicula(peli);
             
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbPeliculas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbSalir;
    // End of variables declaration//GEN-END:variables

private void armarCabecera(){

    modelo.addColumn("Titulo");
    modelo.addColumn("Director");
    modelo.addColumn("Actores");
    modelo.addColumn("Origen");
    modelo.addColumn("Genero");
    modelo.addColumn("Estreno");
    modelo.addColumn("EnCartelera");
     jTable1.setModel(modelo);

}
    
    
    
    
    private void cargarTabla(){
    for (Pelicula peli : peliData.listarPeliculas()) {
        
         modelo.addRow(new Object[]{
             peli.getTitulo(),
             peli.getDirector(),
             peli.getActores(),
             peli.getOrigen(),
             peli.getGenero(),
             peli.getEstreno(),
             peli.isEnCartelera()
        }); 
        
        
    }

}
    
    private void borrarFilas(){
     int numFilas= modelo.getRowCount() -1;
     for (int i = numFilas; i >= 0; i--) {
         modelo.removeRow( i );

     }
 }


}
