/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas1;

/**
 *
 * @author fatimaalcaraz
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
       
        initComponents();
         //setSize(800, 900);
         Escritorio.setSize(800, 900);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        listaPeliculas = new javax.swing.JMenuItem();
        gestionPelicula = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        VistaComprador1 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
<<<<<<< Updated upstream
        jMenu5 = new javax.swing.JMenu();
=======
        menuFuncion = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        ListarFunciones = new javax.swing.JMenuItem();
        menuTikets = new javax.swing.JMenu();
>>>>>>> Stashed changes
        ticket = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        Anular = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Pelicula");

        listaPeliculas.setText("Lista de Peliculas");
        listaPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPeliculasActionPerformed(evt);
            }
        });
        jMenu1.add(listaPeliculas);

        gestionPelicula.setText("Gestion De Pelicula");
        gestionPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(gestionPelicula);

        jMenuItem8.setText("Proximos Estrenos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compradores");

        VistaComprador1.setText("Gestion de Compradores");
        VistaComprador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaComprador1ActionPerformed(evt);
            }
        });
        jMenu2.add(VistaComprador1);

        jMenuItem6.setText("Lista de Compradores");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Sala");

        jMenuItem3.setText("Agregar Sala");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("Eliminar Sala");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar1.add(jMenu4);

<<<<<<< Updated upstream
        jMenu5.setText("Ticket");
=======
        menuFuncion.setText("Funcion");

        jMenuItem1.setText("Gestion de Funcion");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuFuncion.add(jMenuItem1);

        jMenuItem2.setText("Actualizar Funciones");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menuFuncion.add(jMenuItem2);

        ListarFunciones.setText("Funciones Disponibles");
        ListarFunciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarFuncionesActionPerformed(evt);
            }
        });
        menuFuncion.add(ListarFunciones);

        jMenuBar1.add(menuFuncion);

        menuTikets.setText("Ticket");
>>>>>>> Stashed changes

        ticket.setText("Gestion De Ticket");
        ticket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketActionPerformed(evt);
            }
        });
        jMenu5.add(ticket);

        jMenuItem5.setText("Informes De Tickets");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem5);

        jMenuItem7.setText("Lugares Disponibles");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem9.setText("Estadisticas");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        Anular.setText("Anular Ticket");
        Anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnularActionPerformed(evt);
            }
        });
        jMenu5.add(Anular);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 865, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionPeliculaActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        gestionPelicula peli  = new gestionPelicula();
        Escritorio.add(peli);
        peli.setVisible(true);
        Escritorio.moveToFront(peli);
                     
              
    }//GEN-LAST:event_gestionPeliculaActionPerformed

    private void VistaComprador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaComprador1ActionPerformed

        Escritorio.removeAll();
        Escritorio.repaint();
        VistaComprador comprado=new VistaComprador();
        //VistaComprador comprado=new VistaComprador();
        Escritorio.add(comprado);
        comprado.setVisible(true);
        Escritorio.moveToFront(comprado);

        
        
        
    }//GEN-LAST:event_VistaComprador1ActionPerformed

    private void listaPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPeliculasActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        listaPeliculas pelis  = new listaPeliculas();
        Escritorio.add(pelis);
        pelis.setVisible(true);
        Escritorio.moveToFront(pelis);
    }//GEN-LAST:event_listaPeliculasActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
         Escritorio.removeAll();
        Escritorio.repaint();
        VistaSala sala  = new VistaSala();
        Escritorio.add(sala);
        sala.setVisible(true);
        Escritorio.moveToFront(sala);
        
              
        
        
        
        
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        
        
        Escritorio.removeAll();
        Escritorio.repaint();
        VistaSala2 sala2  = new VistaSala2();
        Escritorio.add(sala2);
        sala2.setVisible(true);
        Escritorio.moveToFront(sala2);
        
       
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        vistaFuncion funcion= new vistaFuncion();
        Escritorio.add(funcion);
        funcion.setVisible(true);
        Escritorio.moveToFront(funcion);
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void ticketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketActionPerformed
        
        
        
        Escritorio.removeAll();
        Escritorio.repaint();
        VistasTicket ticket= new VistasTicket();
        Escritorio.add(ticket);
        ticket.setVisible(true);
        Escritorio.moveToFront(ticket);
        
                      
        
        
        
    }//GEN-LAST:event_ticketActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
              
        Escritorio.removeAll();
        Escritorio.repaint();
        ActualizarFunciones funcion = new ActualizarFunciones();
        Escritorio.add(funcion);
        funcion.setVisible(true);
        Escritorio.moveToFront(funcion);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void ListarFuncionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarFuncionesActionPerformed
       Escritorio.removeAll();
       Escritorio.repaint();
       ListaDeFunciones lis = new ListaDeFunciones();
       Escritorio.add(lis);
       lis.setVisible(true);
       Escritorio.moveToFront(lis);
    }//GEN-LAST:event_ListarFuncionesActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        
       Escritorio.removeAll();
       Escritorio.repaint();
       informeTickets informe = new informeTickets();
       Escritorio.add(informe);
       informe.setVisible(true);
       Escritorio.moveToFront(informe);
        
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       
          
       Escritorio.removeAll();
       Escritorio.repaint();
       ListadeCompradores lista = new ListadeCompradores();
       Escritorio.add(lista);
       lista.setVisible(true);
       Escritorio.moveToFront(lista);
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
       
        
       Escritorio.removeAll();
       Escritorio.repaint();
       LugaresDisponibles lugares = new LugaresDisponibles();
       Escritorio.add(lugares);
       lugares.setVisible(true);
       Escritorio.moveToFront(lugares);
        
        
        
        
        
        
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        
       Escritorio.removeAll();
       Escritorio.repaint();
       ProximosEstrenos estrenos = new ProximosEstrenos();
       Escritorio.add(estrenos);
       estrenos.setVisible(true);
       Escritorio.moveToFront(estrenos);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
       
       Escritorio.removeAll();
       Escritorio.repaint();
       Estadisticas estadistica = new Estadisticas();
       Escritorio.add(estadistica);
       estadistica.setVisible(true);
       Escritorio.moveToFront(estadistica);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void AnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnularActionPerformed
     
        
       Escritorio.removeAll();
       Escritorio.repaint();
       Anular anular = new Anular();
       Escritorio.add(anular);
       anular.setVisible(true);
       Escritorio.moveToFront(anular);
        
        
              
        
        
        
        
        
    }//GEN-LAST:event_AnularActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Anular;
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem ListarFunciones;
    private javax.swing.JMenuItem VistaComprador1;
    private javax.swing.JMenuItem gestionPelicula;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem listaPeliculas;
    private javax.swing.JMenu menuFuncion;
    private javax.swing.JMenuItem ticket;
    // End of variables declaration//GEN-END:variables
}
