/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas1;

/**
 *
 * @author fatimaalcaraz
 */
public class vistaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public vistaPrincipal() {
       
        initComponents();
         setSize(800, 600);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        gestionPelicula = new javax.swing.JMenuItem();
        listaPeliculas = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        VistaComprador1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Escritorio.setLayout(null);

        jMenu1.setText("Pelicula");

        gestionPelicula.setText("gestionPelicula");
        gestionPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gestionPeliculaActionPerformed(evt);
            }
        });
        jMenu1.add(gestionPelicula);

        listaPeliculas.setText("Lista de Peliculas");
        listaPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaPeliculasActionPerformed(evt);
            }
        });
        jMenu1.add(listaPeliculas);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compradores");

        VistaComprador1.setText("Gestion de Compradores");
        VistaComprador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VistaComprador1ActionPerformed(evt);
            }
        });
        jMenu2.add(VistaComprador1);

        jMenuItem2.setText("jMenuItem2");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 817, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gestionPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gestionPeliculaActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        gestionPelicula peli  = new gestionPelicula();
        Escritorio.add(peli);
        peli.setVisible(true);
        Escritorio.moveToFront(peli);
                     
              
    }//GEN-LAST:event_gestionPeliculaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       /*
        
        Escritorio.removeAll();
        Escritorio.repaint();
        Vistacomp comprado2=new Vistacomp();
        //VistaComprador comprado=new VistaComprador();
        Escritorio.add(comprado2);
        comprado2.setVisible(true);
        Escritorio.moveToFront(comprado2);
*/
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void VistaComprador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VistaComprador1ActionPerformed

        Escritorio.removeAll();
        Escritorio.repaint();
        VistaComprador comprado=new VistaComprador();
        //VistaComprador comprado=new VistaComprador();
        Escritorio.add(comprado);
        comprado.setVisible(true);
        Escritorio.moveToFront(comprado);

    }//GEN-LAST:event_VistaComprador1ActionPerformed

    private void listaPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaPeliculasActionPerformed
       
        Escritorio.removeAll();
        Escritorio.repaint();
        listaPeliculas pelis  = new listaPeliculas();
        Escritorio.add(pelis);
        pelis.setVisible(true);
        Escritorio.moveToFront(pelis);
    }//GEN-LAST:event_listaPeliculasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Escritorio;
    private javax.swing.JMenuItem VistaComprador1;
    private javax.swing.JMenuItem gestionPelicula;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem listaPeliculas;
    // End of variables declaration//GEN-END:variables
}
