/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas1;

import java.awt.GridLayout;
import java.beans.PropertyVetoException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Comprador;
import modelo.Funcion;
import modelo.Lugar;
import modelo.TicketCompra;
import persistencia.CompradorData;
import persistencia.FuncionData;
import persistencia.LugarData;

import persistencia.TicketCompraData;

/**
 *
 * @author Sutara
 */
public class VistasTicket extends javax.swing.JInternalFrame {

    private FuncionData fundata;
    private TicketCompra ticket;
    private TicketCompraData ticketData;
    private CompradorData compradordata;
    private ButacaArreglo butacaarreglo;
    private LugarData lugardata;
    
    
    public VistasTicket() {
        initComponents();
        
        
        fundata = new FuncionData();
        compradordata = new CompradorData();
        ticketData = new TicketCompraData();
        
        lugardata=new LugarData();
        butacaarreglo=null;
        
        
        llenarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcFuncion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txt3D = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jtDni = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jcMedioPago = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ticket De Compra");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Funcion: ");

        jcFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcFuncionActionPerformed(evt);
            }
        });

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Es 3D");

        txt3D.setEnabled(false);

        btnComprar.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("DNI");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Medio de pago");

        jcMedioPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Debito", "Credito" }));

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(4, 4, 4)))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcFuncion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt3D)
                            .addComponent(jtDni)
                            .addComponent(jcMedioPago, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(195, 195, 195))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt3D, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jcMedioPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed


        
  if(jtDni.getText().trim().isEmpty()){
  
  JOptionPane.showMessageDialog(this, "Debe ingresar el DNI del comprador");
  return;
  
  }      
        
        
        
int dni=Integer.parseInt(jtDni.getText().trim());

        
        
Comprador comprador=compradordata.buscarComprador(dni);



if(comprador==null ){
    
    JOptionPane.showMessageDialog(this, "No se encontro el comprador ");
    return;
    }



Funcion funcion=null;


     if(jcFuncion.getSelectedIndex()>=0){
 funcion=(Funcion) jcFuncion.getSelectedItem();
        
     }else{
     
     JOptionPane.showMessageDialog(null, "Debe elegir una Funcion");
     return;
     }
    
     
     if(butacaarreglo==null){
     
     JOptionPane.showMessageDialog(this, "Debe seleccionar butacas");
     return;
     }
     
     
     
     List<Lugar>seleccionadas=butacaarreglo.getSeleccionadas();
     
     
     
     
     String medioPago=(String) jcMedioPago.getSelectedItem();
     
     if(medioPago==null|| medioPago.isEmpty()){
     
     JOptionPane.showMessageDialog(this, "No se selecciono ninguna butaca");
     }
     
     
     
     if((seleccionadas==null) || seleccionadas.isEmpty()){
    
    JOptionPane.showMessageDialog(this, "No se selecciono ninguna butaca");
    return;
     }
     
     
     
       
         double precio;
         if( funcion.isEs3D()){
             
          precio = 12000;
       
         }else{
         precio = 9000;
         }
     
       
      int cantidad=seleccionadas.size();   
         
     double total=precio*seleccionadas.size();
     
     
     
     int respuesta=JOptionPane.showConfirmDialog(this, "Confirma la compra de " + cantidad + " entradas por un total de " + total, 
             
             "Confirmar compra", JOptionPane.YES_NO_OPTION );
     
     if(respuesta!=JOptionPane.YES_OPTION){
     
     return;
     }
     
     
     
   
     for (Lugar lugar1:seleccionadas){
     
 
     
     
     TicketCompra ticket=new TicketCompra(LocalDate.now(),(int) precio,comprador, funcion,lugar1, medioPago);
    
     
     
             ticketData.comprarTicket(ticket);
             lugar1.setEstado(false);
             lugardata.actualizarEstado(lugar1.getCodLugar(),false);
             
            
             
      
     }
     
      JOptionPane.showMessageDialog(this,"Ticket generado , TOTAL A PAGAR " + total);
     
     
     
     
     
     
    }//GEN-LAST:event_btnComprarActionPerformed

    private void jcFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcFuncionActionPerformed
         
       txt3D.setText(" ");
     if(jcFuncion.getSelectedIndex()>=0){
          
    Funcion fun = (Funcion)jcFuncion.getSelectedItem();
     LugarData lugardata = new LugarData();
    
     
     if(fun.isEs3D()){
     txt3D.setText("Pelicula 3D, precio 12000");
     } else{
     
         txt3D.setText("Pelicula 2D, precio 9000");
     }
     butacaarreglo=new ButacaArreglo(fun,lugardata);
      
      
      if(this.getDesktopPane()!=null){
      
          
 
      this.getDesktopPane().add(butacaarreglo);
      
      butacaarreglo.setVisible(true);
      
      
        
         
         try {
             butacaarreglo.setSelected(true);
         } catch (PropertyVetoException ex) {
             java.util.logging.Logger.getLogger(VistasTicket.class.getName()).log(Level.SEVERE, null, ex);
         }
      }
                 
        
        
        
        
         
     }
    
        
    }//GEN-LAST:event_jcFuncionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox<Funcion> jcFuncion;
    private javax.swing.JComboBox<String> jcMedioPago;
    private javax.swing.JTextField jtDni;
    private javax.swing.JTextField txt3D;
    // End of variables declaration//GEN-END:variables

    public void llenarCombo(){
        
               
        
    
    for (Funcion funcion1: fundata.listarFunciones()){
    
    jcFuncion.addItem(funcion1);
    }
        
        
       
    
    
    }

}
